name: Deploy Jekyll site to Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

env:
  docs_version_path: /
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      - name: Update docs_version_path environment variable
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo docs_version_path=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2) >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' 
          bundler-cache: true 
      # - name: Setup Pages
      #   id: pages
      #   uses: actions/configure-pages@v2
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "/just-the-docs-dev${{ env.docs_version_path }}"
        env:
          JEKYLL_ENV: production
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          target-folder: ${{ env.docs_version_path }}
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: '["version"]'
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      

  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
